export const PERMISSIONS = {
  // Workspace
  MANAGE_WORKSPACE: "manage_workspace",
  MANAGE_MEMBERS: "manage_members",
  VIEW_WORKSPACE: "view_workspace",

  // Accounts
  CREATE_ACCOUNT: "create_account",
  UPDATE_ACCOUNT: "update_account",
  DELETE_ACCOUNT: "delete_account",
  VIEW_ACCOUNTS: "view_accounts",

  // Transactions
  CREATE_TRANSACTION: "create_transaction",
  UPDATE_TRANSACTION: "update_transaction",
  DELETE_TRANSACTION: "delete_transaction",
  VIEW_TRANSACTIONS: "view_transactions",

  // Categories
  MANAGE_CATEGORIES: "manage_categories",

  // Budgets
  CREATE_BUDGET: "create_budget",
  UPDATE_BUDGET: "update_budget",
  DELETE_BUDGET: "delete_budget",
  VIEW_BUDGETS: "view_budgets",

  // Goals
  CREATE_GOAL: "create_goal",
  UPDATE_GOAL: "update_goal",
  DELETE_GOAL: "delete_goal",
  VIEW_GOALS: "view_goals",

  // Investments
  CREATE_INVESTMENT: "create_investment",
  UPDATE_INVESTMENT: "update_investment",
  DELETE_INVESTMENT: "delete_investment",
  VIEW_INVESTMENTS: "view_investments",

  // Reports
  GENERATE_REPORTS: "generate_reports",
  VIEW_REPORTS: "view_reports",

  // AI
  USE_AI: "use_ai",

  // Admin
  ADMIN: "admin",
};

export const DEFAULT_ROLE_PERMISSIONS = {
  owner: Object.values(PERMISSIONS),

  admin: [
    PERMISSIONS.VIEW_WORKSPACE,
    PERMISSIONS.MANAGE_MEMBERS,

    PERMISSIONS.CREATE_ACCOUNT,
    PERMISSIONS.UPDATE_ACCOUNT,
    PERMISSIONS.DELETE_ACCOUNT,
    PERMISSIONS.VIEW_ACCOUNTS,

    PERMISSIONS.CREATE_TRANSACTION,
    PERMISSIONS.UPDATE_TRANSACTION,
    PERMISSIONS.DELETE_TRANSACTION,
    PERMISSIONS.VIEW_TRANSACTIONS,

    PERMISSIONS.MANAGE_CATEGORIES,

    PERMISSIONS.CREATE_BUDGET,
    PERMISSIONS.UPDATE_BUDGET,
    PERMISSIONS.DELETE_BUDGET,
    PERMISSIONS.VIEW_BUDGETS,

    PERMISSIONS.CREATE_GOAL,
    PERMISSIONS.UPDATE_GOAL,
    PERMISSIONS.DELETE_GOAL,
    PERMISSIONS.VIEW_GOALS,

    PERMISSIONS.CREATE_INVESTMENT,
    PERMISSIONS.UPDATE_INVESTMENT,
    PERMISSIONS.DELETE_INVESTMENT,
    PERMISSIONS.VIEW_INVESTMENTS,

    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_REPORTS,

    PERMISSIONS.USE_AI,
  ],

  member: [
    PERMISSIONS.VIEW_WORKSPACE,

    PERMISSIONS.VIEW_ACCOUNTS,

    PERMISSIONS.CREATE_TRANSACTION,
    PERMISSIONS.UPDATE_TRANSACTION,
    PERMISSIONS.VIEW_TRANSACTIONS,

    PERMISSIONS.VIEW_BUDGETS,

    PERMISSIONS.VIEW_GOALS,

    PERMISSIONS.VIEW_INVESTMENTS,

    PERMISSIONS.VIEW_REPORTS,

    PERMISSIONS.USE_AI,
  ],

  viewer: [
    PERMISSIONS.VIEW_WORKSPACE,
    PERMISSIONS.VIEW_ACCOUNTS,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_BUDGETS,
    PERMISSIONS.VIEW_GOALS,
    PERMISSIONS.VIEW_INVESTMENTS,
    PERMISSIONS.VIEW_REPORTS,
  ],
};